name: Deploy to AWS S3

on:
  push:
    branches:
      - auth

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Install Dependencies
        run: |
          yarn install

      - name: 서브모듈 가져오기
        run: |
          git submodule update --init --recursive

      - name: 프로젝트 빌드
        run: |
          cd services/auth && yarn build
        
        env:
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          REACT_APP_CHANNEL_PLUGIN: ${{ secrets.REACT_APP_CHANNEL_PLUGIN }}

      - name: 빌드파일 배포
        run: |
          cd services/auth
          aws s3 sync dist/auth s3://${{ secrets.AWS_AUTH_BUCKET }}/auth
          aws s3 sync dist/index s3://${{ secrets.AWS_AUTH_BUCKET }}

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2